leftnav:
- identifier: c86813c9-54cd-0219-7c73-c9b3c7311005
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 5b3e87b2-5cf9-3ec1-76c3-a8c4681340dd
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 03f5aa4c-2226-6d13-da8f-c421c41a6552
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 099e401c-a3ad-e2c3-393e-e03f278ab207
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 559f3c2a-8c7a-1dc3-9fd5-4680f0a88796
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
